name: Build latest image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go 1.18
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.x'

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.45.0
        args: -p bugs -p unused --timeout=3m

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/metal-stack/metal-metrics-exporter .

    - name: Push Docker image
      run: |
        docker push ghcr.io/metal-stack/metal-metrics-exporter

    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
