name: Build image from pull request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go 1.18
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.x'

    - name: Figure out if running fork PR
      id: fork
      run: '["${{ secrets.DOCKER_REGISTRY_TOKEN }}" == ""] && echo "::set-output name=is_fork_pr::true" || echo "::set-output name=is_fork_pr::false"'

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      if: steps.fork.outputs.is_fork_pr == 'false'

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.45.0
        args: -p bugs -p unused --timeout=3m

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/metal-stack/metal-metrics-exporter:pr-${GITHUB_HEAD_REF##*/} .

    - name: Push Docker image
      run: |
        # pull request images are prefixed with 'pr' to prevent them from overriding released images
        docker push ghcr.io/metal-stack/metal-metrics-exporter:pr-${GITHUB_HEAD_REF##*/}
      if: steps.fork.outputs.is_fork_pr == 'false'
