name: Build image from release tag

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go 1.20
      uses: actions/setup-go@v3
      with:
        go-version: '1.20.x'

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.50.1
        args: -p bugs -p unused --timeout=3m

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/metal-stack/metal-metrics-exporter:${GITHUB_REF##*/} .
        docker push ghcr.io/metal-stack/metal-metrics-exporter:${GITHUB_REF##*/}
